# Generated by Django 4.0.6 on 2022-08-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_user_level_user_through_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='through_num',
            new_name='cleanTrashNumber',
        ),
    ]
