# Generated by Django 4.0.6 on 2022-08-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rank_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank_app.place')),
            ],
        ),
    ]
