# Generated by Django 4.0.4 on 2022-08-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('student_num', models.IntegerField(default=0, null=True)),
                ('throw_num', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
