# Generated by Django 4.0.6 on 2022-08-27 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='univ_photo')),
                ('student_num', models.IntegerField(default=0, null=True)),
                ('throw_num', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trashcan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trashcan_number', models.IntegerField()),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank_app.place')),
            ],
        ),
        migrations.CreateModel(
            name='Throwing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('trashcan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank_app.place')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
